name: Monnify Node.js Library CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
  
      env:
        NODE_ENV: sandbox
        APIKEY: MK_TEST_SJA0T1Q5A0
        MONNIFY_SECRET_KEY: YKLEHB5DK3U1SAEKGWWVK182QVCSZETB
        CONTRACT: 3627340743
        WALLETACCOUNTNUMBER: 8622792723
        BASE_URL: https://sandbox.monnify.com

      run: npm test
