name: Monnify Node.js Library CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install dependencies (clean)
      run: npm ci

    - name: Create .env file
      run: |
        echo "NODE_ENV=sandbox" >> .env
        echo "APIKEY=MK_TEST_SJA0T1Q5A0" >> .env
        echo "SECRET=YKLEHB5DK3U1SAEKGWWVK182QVCSZETB" >> .env
        echo "CONTRACT=3627340743" >> .env
        echo "WALLETACCOUNTNUMBER=8622792723" >> .env
        echo "BASE_URL=https://sandbox.monnify.com" >> .env

    - name: Verify installed packages
      run: npm list

    - name: Run tests

      run: npm test
